server:
  port: 8082

spring:
  application:
    name: consumer-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: analytics-consumer-group
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/analytics}
    username: ${SPRING_DATASOURCE_USERNAME:analytics_user}
    password: ${SPRING_DATASOURCE_PASSWORD:analytics_pass}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  kafka:
    topic: order-events
