server:
  port: 8081

spring:
  application:
    name: producer-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  kafka:
    topic: order-events
  generator:
    auto-enabled: true
    auto-batch-size: 8
    auto-interval-ms: 15000
